propiedad:
  ejemplo: Hola Docker


spring:
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/clientes
    username: clientes
    password: '{cipher}8110111cb5e8229f63158584da85131166a88678adc6611d855bcbc4fe6481be'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/