propiedad:
  ejemplo: Hola AWS


spring:
  datasource:
    url: jdbc:mysql://database-abc.c4mechwnechh.us-east-1.rds.amazonaws.com:3306/prestamos
    username: prestamos
    password: '{cipher}8110111cb5e8229f63158584da85131166a88678adc6611d855bcbc4fe6481be'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# URI Authorization Server
openid:
  jwt:
    # Configuracion para Keycloak
    # issuerUri: http://localhost:8080/realms/abc-realm
    # Configuracion para Spring Authorization Server
    issuerUri: http://localhost:8080