propiedad:
  ejemplo: Hola Desa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prestamos
    username: prestamos
    password: '{cipher}8110111cb5e8229f63158584da85131166a88678adc6611d855bcbc4fe6481be'

